### ISSUE TITLE
Go vanity import URLs not working

### ISSUE THREAD

**Issue by kkoreilly** [goki/goki.github.io#1]
It is failing with a cryptic error; for example: `go: unrecognized import path "goki.dev/gi": parsing goki.dev/gi: XML syntax error on line 1: expected /> in element`

**Comment by kkoreilly** [comment]
The solution to this is to set `keepQuotes` to `true` in the `minify.tdewolff.html` settings. Without this, the Go tool XML parser fails on unquoted links with the cryptic error above. For example:
```toml
[minify]
[minify.tdewolff]
[minify.tdewolff.html]
keepQuotes = true
```
